services:
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandbox
    ports:
      - '2222:2222'
    volumes:
      - ./ssh_key.pub:/home/dev/.ssh/authorized_keys:ro
      - ./fixtures:/home/dev/fixtures
      - empty-fixtures:/home/dev/fixtures/empty
      - dev-home:/home/dev/workspace
    restart: unless-stopped
    hostname: sandbox

  # kind (Kubernetes in Docker) control plane
  kind-control-plane:
    image: kindest/node:v1.31.0
    container_name: kind-control-plane
    privileged: true
    restart: unless-stopped
    volumes:
      - /var
      - /lib/modules:/lib/modules:ro
    tmpfs:
      - /tmp
      - /run
    networks:
      - kind
    environment:
      - KUBECONFIG=/etc/kubernetes/admin.conf

volumes:
  dev-home:
  empty-fixtures:

networks:
  kind:
    driver: bridge
