version: 2.1

orbs:
  node: circleci/node@7.2.1

executors:
  node:
    docker:
      - image: cimg/node:24.9

jobs:
  lint:
    executor: node
    steps:
      - checkout
      - node/install-pnpm
      - node/install-packages:
          pkg-manager: pnpm
      - run: pnpm lint
  test:
    machine:
      image: ubuntu-2404:2025.09.1
    steps:
      - checkout
      - run: cd sandbox && docker compose up -d
      - run: docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Names}}\t{{.Networks}}"
      - node/install:
          install-pnpm: true
          node-version: '24.9'
      - node/install-packages:
          pkg-manager: pnpm
      - run: pnpm test
  build:
    executor: node
    steps:
      - checkout
      - node/install-pnpm
      - node/install-packages:
          pkg-manager: pnpm
      - run: pnpm build

workflows:
  integration:
    jobs:
      - lint
      - test
      - build
