version: 2.1

orbs:
  node: circleci/node@7.2.1

executors:
  node:
    docker:
      - image: cimg/node:24.9

jobs:
  lint:
    executor: node
    steps:
      - checkout
      - node/install-pnpm
      - node/install-packages:
          pkg-manager: pnpm
      - run: pnpm lint
  test:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: cd sandbox && docker compose up -d
      - node/install-pnpm
      - node/install-packages:
          pkg-manager: pnpm
      - run: pnpm test
  build:
    executor: node
    steps:
      - checkout
      - node/install-pnpm
      - node/install-packages:
          pkg-manager: pnpm
      - run: pnpm build

workflows:
  integration:
    jobs:
      - lint
      - test
      - build
